# Config file for automatic testing at travis-ci.org

language: python
sudo: false


notifications:
  email:
    - ctunnell@nikhef.nl
    - jaalbers@nikhef.nl
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/09d571df0e21d4d4182f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

services:
  - mongodb

matrix:
  allow_failures:
    - os: osx 
  include:
    -language: generic
    os: osx
    env: TRAVIS_PYTHON_VERSION=2.7
    env: ROOT=5
    -language: generic
    os: osx
    env: TRAVIS_PYTHON_VERSION=3.4
    env: ROOT=5
    -language: generic
    os: osx
    env: TRAVIS_PYTHON_VERSION=2.7
    env: ROOT=6
    -language: generic
    os: osx
    env: TRAVIS_PYTHON_VERSION=3.4
    env: ROOT=6
    - python: 2.7
    env: 
      - ROOT=5
      - ROOT=6
    addons:
      apt:
        sources:
      	- ubuntu-toolchain-r-test
      	packages:
      	- build-essential
      	- git
      	- dpkg-dev
      	- make
      	- binutils
      	- libx11-dev
      	- libxpm-dev
      	- libxft-dev
      	- libxext-dev
      	- gcc-multilib
      	#    - libsnappy1
      	#    - libsnappy-dev
      	- python-software-properties
      	- gcc-4.8
      	- g++-4.8
    - python: 3.4
    env: 
      - ROOT=5
      - ROOT=6
    addons:
      apt:
        sources:
      	- ubuntu-toolchain-r-test
      	packages:
        - build-essential
        - git
        - dpkg-dev
        - make
        - binutils
        - libx11-dev
        - libxpm-dev
        - libxft-dev
        - libxext-dev
        - gcc-multilib
        - python-software-properties
        - gcc-4.8
        - g++-4.8


before_install:
  - brew update

install:
  - deactivate
  - gcc --version

  # Conda
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then brew install wget; fi
  - wget -nv http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda
  - conda config --add channels http://conda.anaconda.org/NLeSC  
  - conda create -q -n pax python=$TRAVIS_PYTHON_VERSION root=${ROOT} numpy scipy matplotlib pandas cython h5py numba pip python-snappy pytables scikit-learn
  - source activate pax
  - pip install coveralls nose coverage

  # Install pax
  - python setup.py install
  
  # Run a simple test file, to see if the tests load
  # If there is an import failure, you don't get to know which import is failing otherwise
  - python tests/test_maxpmt.py

# command to run tests, e.g. python setup.py test
script:
  - make test
#  - make coverage
  - make lint

#after_success:
#  - coveralls

