# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
#  - "pypy"

notifications:
  email:
    - ctunnell@nikhef.nl
    #- jaalbers@nikhef.nl
    #- bartp@nikhef.nl

env:
  #- ROOT=5.32.04
  - ROOT=5.34.25
  #- ROOT=6.02.04

install:
  # General update
  - sudo apt-get update -qq
  - yes | sudo apt-get upgrade

  # MiniConda
  - wget -nv http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda

  # Create environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytables
  - source activate test-environment

  # ROOT
  - sudo apt-get install -y git dpkg-dev make binutils libx11-dev libxpm-dev libxft-dev libxext-dev gcc-multilib
  - sudo apt-get install git dpkg-dev make g++ gcc binutils libx11-dev libxpm-dev libxft-dev libxext-dev
  - sudo apt-get install gfortran libssl-dev libpcre3-dev xlibmesa-glu-dev libglew1.5-dev libftgl-dev libmysqlclient-dev libfftw3-dev cfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev python-dev libxml2-dev libkrb5-dev libgsl0-dev libqt4-dev
  - time wget -nv --no-check-certificate http://root.cern.ch/download/root_v${ROOT}.source.tar.gz
  - tar xfz root_v${ROOT}.source.tar.gz root
  - cd root
  #- find $HOME/miniconda/envs/test-environment/lib
  #- find $HOME/miniconda/envs/test-environment/include
  - python3.4-config --configdir --includes --cflags --ldflags --exec-prefix
  - ln -s `python3.4-config --exec-prefix`/lib/libpython3.4m.so  `python3.4-config --exec-prefix`/lib/libpython3.4.so
  - ./configure --enable-python --with-python-incdir=`python3.4-config --exec-prefix`/include/python3.4m --with-python-libdir=`python3.4-config --exec-prefix`/lib
  - cat config.log
  - make install
  #- sudo updatedb
  - python -m ROOT

  # Install pax
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make lint
