# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"
#  - "pypy"

notifications:
  email:
    - ctunnell@nikhef.nl
    - jaalbers@nikhef.nl
    - bartp@nikhef.nl

env:
  #- ROOT=6.02.04
  #- ROOT=5.32.04
  - ROOT=5.34.25

install:
  # General update
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y git dpkg-dev make binutils libx11-dev libxpm-dev libxft-dev libxext-dev gcc-multilib g++ gcc libsnappy1 libsnappy-dev
  #- yes | sudo apt-get upgrade

  # MiniConda
  - wget -nv http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda

  # Install snappy and python bindings
  - sudo apt-get install libsnappy-dev
  - sudo apt-get build-dep python-snappy

  # Create environment
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytables
  - source activate test-environment

  # ROOT 
  # - unset ROOT # uncomment to not install ROOT
  - if test -n "$ROOT"; then source .travis-install-ROOT.sh; fi

  -echo test if ROOT is working...
  -root -l -q
  -python -c "import ROOT; ROOT.TBrowser()"

  # What is the ROOT.py we are using?????????
  -echo ROOT.py ==============================================================
  -cat /home/travis/build/XENON1T/pax/root/lib/ROOT.py
  -echo ======================================================================

  # Copy custom ROOT.py to proper directory
  - if test -n "$ROOT"; then cp /home/travis/build/XENON1T/pax/travis_custom_ROOT.py /home/travis/build/XENON1T/pax/root/lib/ROOT.py; fi

  # Does pyROOT still work?
  -root -l -q
  -python -c "import ROOT; ROOT.TBrowser()"

  - conda install system

  # Install pax
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make lint
