# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.4"

notifications:
  email:
    - ctunnell@nikhef.nl
    #- jaalbers@nikhef.nl
    #- bartp@nikhef.nl

services:
  - mongodb

env:
  - ROOT=5.34.25


install:
  # General update
  - deactivate
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y git dpkg-dev make binutils libx11-dev libxpm-dev libxft-dev libxext-dev gcc-multilib g++ gcc libsnappy1 libsnappy-dev
  #- yes | sudo apt-get upgrade

  # MiniConda
  - wget -nv http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a # Useful for debugging any issues with conda

  # Install snappy and python bindings
  - sudo apt-get install libsnappy-dev
  - sudo apt-get build-dep python-snappy

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pytables pip
  #- pip uninstall -y nose

  - source activate test-environment
  - pip install coveralls nose coverage

   # Install pax
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - make test
  - make coverage
  - make lint

after_success:
  coveralls

